#voting app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "votingapp_helm.fullname" . }}-voting-app
  labels:
    {{- include "votingapp_helm.labels" . | nindent 4 }}
    name: {{ .Values.labelsAll }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "votingapp_helm.selectorLabels" . | nindent 6 }}-voting-app
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "votingapp_helm.selectorLabels" . | nindent 8 }}-voting-app
    spec:
      containers:
        - name: {{ .Chart.Name }}-voting-app
          image: "{{ .Values.imageVotingApp.repository }}:{{ .Values.imageVotingApp.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.serviceVotingApp.port }}
---