#voting app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labelVotingApp }}-deployment
  labels:
    name: {{ .Values.labelVotingApp }}-deploy
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      name: {{ .Values.labelVotingApp }}-deploy
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        name: {{ .Values.labelVotingApp }}-deploy
        app: {{ .Values.labelsAll }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-voting-app
          image: "{{ .Values.imageVotingApp.repository }}:{{ .Values.imageVotingApp.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.serviceVotingApp.port }}
---