apiVersion: v1
kind: Service
metadata:
  name: {{ include "votingapp_helm.fullname" . }}-voting-app-service
  labels:
    {{- include "votingapp_helm.labels" . | nindent 4 }}-voting-app-service
    name: {{ .Values.labelsAll }}
spec:
  type: {{ .Values.serviceVotingApp.type }}
  {{- if eq .Values.serviceVotingApp.type "NodePort" }}
  ports:
    - port: {{ .Values.serviceVotingApp.port }}
      targetPort: {{ .Values.serviceVotingApp.port }}
      protocol: TCP
      nodePort: {{ .Values.serviceVotingApp.nodePort }}
  selector:
    {{- include "votingapp_helm.labels" . | nindent 4 }}-voting-app-service
    name: {{ .Values.labelsAll }}
  {{- else }}
  {{ end }}
