# service Voting-app
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labelVotingApp }}-service
  labels:
    name: {{ .Values.labelVotingApp }}-service
    app: {{ .Values.labelsAll }}
spec:
  type: {{ .Values.serviceVotingApp.type }}
  {{- if eq .Values.serviceVotingApp.type "NodePort" }}
  ports:
    - port: {{ .Values.serviceVotingApp.port }}
      targetPort: {{ .Values.serviceVotingApp.port }}
      protocol: TCP
      nodePort: {{ .Values.serviceVotingApp.nodePort }}
  selector:
    name: {{ .Values.labelVotingApp }}-deploy
    app: {{ .Values.labelsAll }}
  {{- else }}
  ports:
    - port: {{ .Values.serviceVotingApp.port }}
      targetPort: {{ .Values.serviceVotingApp.port }}
      protocol: TCP
  selector:
    name: {{ .Values.labelVotingApp }}-deploy
    app: {{ .Values.labelsAll }}
  {{ end }}
---
# service result app
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labelResultApp }}-service
  labels:
    name: {{ .Values.labelResultApp }}-service
    app: {{ .Values.labelsAll }}
spec:
  type: {{ .Values.serviceResultApp.type }}
  {{- if eq .Values.serviceResultApp.type "NodePort" }}
  ports:
    - port: {{ .Values.serviceResultApp.port }}
      targetPort: {{ .Values.serviceResultApp.port }}
      protocol: TCP
      nodePort: {{ .Values.serviceResultApp.nodePort }}
  selector:
    name: {{ .Values.labelResultApp }}-deploy
    app: {{ .Values.labelsAll }}
  {{- else }}
  ports:
    - port: {{ .Values.serviceResultApp.port }}
      targetPort: {{ .Values.serviceResultApp.port }}
      protocol: TCP
  selector:
    name: {{ .Values.labelResultApp }}-deploy
    app: {{ .Values.labelsAll }}
  {{ end }}